CREATE TABLE users (
    userid NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(50) NOT NULL,
    name VARCHAR2(100),
    email VARCHAR2(100)
);


CREATE TABLE Bus (
    busId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    busName VARCHAR2(50) NOT NULL,
    busType VARCHAR2(50) NOT NULL,
    source VARCHAR2(50) NOT NULL,
    destination VARCHAR2(50) NOT NULL,
    departureDate VARCHAR2(50) NOT NULL,
    arrivalDate VARCHAR2(50) NOT NULL,
    totalSeats NUMBER NOT NULL,
    price NUMBER NOT NULL
);


-- Passenger table
CREATE TABLE Passenger (
    userId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userName VARCHAR2(100) NOT NULL,
    passwd VARCHAR2(100) NOT NULL,
    mobileNo VARCHAR(100) NOT NULL,
    emailId VARCHAR2(100) NOT NULL, 
    walletBalance NUMBER(20)
);


CREATE TABLE Transaction (
    transactionId NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL,
    emailId VARCHAR2(100) NOT NULL,
    busId NUMBER,
    busName VARCHAR2(100) NOT NULL,
    noOfBookedSeats NUMBER(20) NOT NULL,
    pricePerSeat NUMBER(20) NOT NULL,
    totalPrice NUMBER NOT NULL,
    bookingDate DATE NOT NULL
);


-- Booked seats table
-- CREATE TABLE booked_seats (
--     id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     ticket_id NUMBER NOT NULL,
--     buyer_name VARCHAR2(100) NOT NULL,
--     paid BOOLEAN DEFAULT FALSE,
--     booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
-- );
